---
title: "Supplementary Information" 
subtitle: "State Self-Compassion Dynamics: Partial Evidence for the Bipolar Continuum Hypothesis"
format: 
    pdf:
      toc: true
      toc-depth: 2
      number-sections: true
      geometry: "left=3cm,right=3cm,top=2.5cm,bottom=2.5cm"
      header-includes: |
         \usepackage{fancyhdr}
         \pagestyle{fancy}
         \fancyhead[L]{Supplementary Information}
      bibliography: bibliography.bib
      cls: apa7.cls
---

```{r}
#| include = FALSE
#|
suppressPackageStartupMessages({
  library("here")
  library("dplyr")
  library("brms")
  library("bayesplot")
  library("effectsize")
  library("scales")
  library("sjstats")
  library("sjPlot")
  library("sjmisc")
  library("emmeans")
  library("quarto")
  library("knitr")
  library("kableExtra")
})
```

\newpage

# Study 1

## Baseline Measures

{{< include ./sections/apx_study1_descriptive_stats.qmd >}}

\newpage

## EMA Survey Questions

{{< include ./sections/apx_study1_survey_questions.qmd >}}

\newpage

## Data Quality Management and Subject Selection 

{{< include ./sections/apx_careless_study1.qmd >}}

\newpage

## Analysis 1: Correlations Between the CS and UCS Components

{{< include ./sections/apx_study1_correlations.qmd >}}

\newpage

## Analysis 2: Multilevel Reliability

{{< include ./sections/apx_study1_reliability.qmd >}}

\newpage

## Analysis 3: Impact of Contextual Influences on CS and UCS

{{< include ./sections/apx_study1_model_comparison_piel.qmd >}}

\newpage

## Supplementary Analysis: Nomothetic Evaluation of the CS-UCS Relationship {#sec-nomothetic-an-study1}

{{< include ./sections/apx_study1_bip_cont_hyp.qmd >}}

\newpage


# Study 2

## Baseline Measures

{{< include ./sections/apx_study2_descriptive_stats.qmd >}}

\newpage

## EMA Survey Questions

{{< include ./sections/apx_study2_survey_questions.qmd >}}

\newpage

## Data Quality Management and Subject Selection 

{{< include ./sections/apx_careless_study2.qmd >}}


<!-- ## Model Convergence Diagnostics -->

<!-- {{< include ./sections/apx_study2_model_convergence_diag.qmd >}} -->

\newpage

## Analysis 1: Impact of Academic Exam on State Self-Compassion

{{< include ./sections/apx_study2_exam_ssc.qmd >}}

\newpage

### Supplementary Analysis: Impact of Academic Exam on Negative Affect  

{{< include ./sections/apx_study2_impact_of_exam_on_neg_aff.qmd >}}

\newpage

## Analysis 2: Impact of Contextual Influences on CS and UCS

{{< include ./sections/apx_study2_model_comparison_mpath.qmd >}}

\newpage

## Supplementary Analysis: Nomothetic Evaluation of the CS-UCS Relationship 

{{< include ./sections/apx_study2_direct_test.qmd >}}

\newpage

## Analysis 3: Levels of Personal Concern

{{< include ./sections/apx_study2_personal_concerns.qmd >}}

\newpage

## Analysis 4: Decentering and SC and USC Correlation  

{{< include ./sections/apx_study2_decentering.qmd >}}

\newpage

# Both Studies Combined

## Dimensionality Test 

{{< include ./sections/apx_rev1_cfa_multilevel.qmd >}}

\newpage

## Idionomic Analysis

{{< include ./sections/apx_rev1_idionomic.qmd >}}

\pagebreak

## Examining Response Bias 

{{< include ./sections/apx_response_bias.qmd >}}

\pagebreak

## References
